GET http://http://localhost:3000/api/Contacts

###

POST http://http://localhost:3000/api/Contact
Content-Type: application/json

{
    "text": "Get the bread"
}

###

DELETE http://http://localhost:3000/api/Contact/asdfdf